/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Black Ink (https://sketchfab.com/blackink)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/air-jordan-1-retro-high-obsidian-unc-ab3c68bb7fb94d80b59a713990fcbae1
title: Air Jordan 1 Retro High Obsidian UNC
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/jordan.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={20}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['main_object.001.mat']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/jordan.gltf')
