export const CREATE_SHOE = "CREATE_SHOE";
export const RETRIEVE_SHOES = "RETRIEVE_SHOES";
export const UPDATE_SHOE = "UPDATE_SHOE";
export const DELETE_SHOE = "DELETE_SHOE";
export const DELETE_ALL_SHOES = "DELETE_ALL_SHOES";